// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9M0orr8hQCOmQGe0Gd2zYugM8RaOwA_0',
    appId: '1:1087077452782:web:ff05cab0c6c4769515cff',
    messagingSenderId: '1087077452782',
    projectId: 'flutter-movies-cf359',
    authDomain: 'flutter-movies-cf359.firebase.com',
    storageBucket: 'flutter-movies-cf359.apps pot.com',
    measurementId: 'G-KVMZVRSJTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC25erVuyY_D1Rt-x53u8QuwSaItkZQCoo',
    appId: '1:1087077452782:android:385489836b74b700515cff',
    messagingSenderId: '1087077452782',
    projectId: 'flutter-movies-cf359',
    storageBucket: 'flutter-movies-cf359.apps pot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGXeNwt60C6mS65cVxP0zVDMJPA8C7tAo',
    appId: '1:1087077452782:ios:ad966038b8f3da36515cff',
    messagingSenderId: '1087077452782',
    projectId: 'flutter-movies-cf359',
    storageBucket: 'flutter-movies-cf359.apps pot.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGXeNwt60C6mS65cVxP0zVDMJPA8C7tAo',
    appId: '1:1087077452782:ios:a6b7b48880a4001f515cff',
    messagingSenderId: '1087077452782',
    projectId: 'flutter-movies-cf359',
    storageBucket: 'flutter-movies-cf359.apps pot.com',
    iosBundleId: 'com.example.moviesApp.RunnerTests',
  );
}
